baseURL = "http://example.org/"
languageCode = "en-us"
title = "On3 Events"

theme = "on3-tailwind"

[Social]
    instagram = "https://www.instagram.com/On3events/"
    linkedin = "https://www.linkedin.com/company/on-3-events/"